# Generated by Django 3.0 on 2019-12-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('I', models.CharField(max_length=1000)),
                ('T', models.CharField(max_length=1000)),
                ('Time', models.CharField(max_length=1000)),
                ('predict_result', models.CharField(max_length=1000)),
            ],
        ),
    ]
